baseURL = "https://example.com"
title = "Digitalentosa"
author = "Digitalentosa"
copyright = "© Digitalentosa - Origin Theme"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin"

[languages]
  [languages.en]
    title = "Digitalentosa"
    contentDir = "content/english"
    weight = 1
    [languages.en.params]
    description = "Digigodness"
  [languages.pt-br]
    title = "Digitalentosa"
    contentDir = "content/portuguese"
    weight = 2
    [languages.pt-br.params]
    description = "Digideusas"
  [languages.es]
    title = "Digitalentosa"
    contentDir = "content/spanish"
    weight = 2
    [languages.es.params]
    description = "digidiosas"   


[params]
  description = "digitalgoood"
  featured = true
  cssonly = false

  [params.socials]
    twitter = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

enableEmoji = true

ignoreErrors = ["error-remote-getjson"]


